### ISSUE TITLE
How to write this open source project？

### ISSUE THREAD

**Issue by shizongger** [bshannon/JavaMail#2]
Respect of the open source community contributor, I'm a Java developers from China. My university undergraduate course studies is the computer science and technology, because the university is not a top university in China, so my knowledge of computer and the technology is not a lot, but also learn some professional knowledge, such as C/C + + programming language, assembly language, Data Structure domain algorithm and so on.

Finally, I went into javaee development, a year and a half from graduation, and learned to use Spring,Spring MVC, MyBatis, and other skills to develop enterprise-level projects for service business logic.I'd like to join the open source community, and I've seen JavaMail in the last few days. After reading her API and writing some demo, I can basically use JavaMail to send and receive an E-mail.

I want to become a good prammager, and wanna be a Open Source contributor. Wanna join this open source project, can you please guide me how to start?What's the Java skills and references requires on this project?

**Comment by bshannon** [comment]
First, the real JavaMail project is [here](https://javaee.github.io/javamail/).  You'll find instructions on how to [contribute](https://javaee.github.io/javamail/Contributions) to that project.

In general, you should use the [mailing list](https://javaee.groups.io/g/javamail) to ask questions, not create new issues.

Note also that we're in the process of contributing all of the Java EE projects to the Eclipse Foundation under the [EE4J](https://projects.eclipse.org/projects/ee4j) project.  In the next several months, all development work will move to the Eclipse Foundation, following their rules for contributions to projects.
