### ISSUE TITLE
java mail 1.2

### ISSUE THREAD

**Issue by MuzDing** [bshannon/JavaMail#3]
Do you have the source code of Java mail1.2? I'm learning java mail and I find that the new version is different from the old one. I've made some changes. I want to see.

**Comment by bshannon** [comment]
JavaMail 1.2 was not available under an open source license.  If you're learning JavaMail,
why did you start with version 1.2?  Do you have a specific issue with the current version?
If you have a question about JavaMail, see the [JavaMail web site](https://javaee.github.io/javamail/#Help).
