### ISSUE TITLE
Return value problem

### ISSUE THREAD

**Issue by MuzDing** [bshannon/JavaMail#4]
I have already got a general idea of the situation, thank you for your suggestion.
Because I recently used Javamail1.6, I found that the getContent() method in the MimeBodyPart class in 1.6 returns an array. The 1.2 I used originally returned is a MimeBodyPart object, so I want to take a look at javamail 1.2. How is it defined?
excuse me.

**Comment by bshannon** [comment]
Please stop using issues as an email system.

The getContent() method returns a data type appropriate to the content of the
body part, often a String.  It never returns a MimeBodyPart.  It might return a
byte array in some cases.
